<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="2.0" 
                xmlns:html="http://www.w3.org/TR/REC-html40"
                xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
                xmlns:aa="http://activeaway.com/schemas/sitemap"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
  <xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>
  <xsl:template match="/">
    <html xmlns="http://www.w3.org/1999/xhtml">
      <head>
        <title>Active Away XML Sitemap</title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <style type="text/css">
          body {
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen-Sans, Ubuntu, Cantarell, "Helvetica Neue", sans-serif;
            color: #333;
            margin: 0;
            padding: 0;
            background: #f9f9fa;
          }
          header {
            background-color: #0D1C4E; /* Active Away Navy */
            color: white;
            padding: 30px 40px;
            margin-bottom: 40px;
          }
          h1 {
            margin: 0;
            font-size: 24px;
            font-weight: 600;
            display: flex;
            align-items: center;
          }
          p.desc {
            margin: 10px 0 0;
            font-size: 14px;
            opacity: 0.8;
            line-height: 1.5;
          }
          a {
            color: #0D1C4E;
            text-decoration: none;
          }
          a:hover {
            text-decoration: underline;
            color: #ad986c; /* Active Away Gold */
          }
          #content {
            max-width: 1200px;
            margin: 0 auto;
            padding: 0 20px;
            background: white;
            box-shadow: 0 1px 3px rgba(0,0,0,0.1);
            border-radius: 4px;
            margin-bottom: 40px;
          }
          table {
            width: 100%;
            border-collapse: collapse;
            font-size: 14px;
          }
          th {
            text-align: left;
            padding: 15px 20px;
            border-bottom: 1px solid #eee;
            font-weight: 600;
            color: #666;
            font-size: 12px;
            text-transform: uppercase;
            letter-spacing: 0.5px;
            background: #fafafa;
          }
          td {
            padding: 12px 20px;
            border-bottom: 1px solid #eee;
          }
          tr:last-child td {
            border-bottom: none;
          }
          tr:hover td {
            background-color: #f8f9fa;
          }
          .count-tag {
            display: inline-block;
            background: rgba(255,255,255,0.2);
            padding: 4px 12px;
            border-radius: 20px;
            font-size: 14px;
            margin-left: 15px;
            font-weight: normal;
          }
          .url-count {
            display: inline-block;
            background: #eee;
            padding: 2px 8px;
            border-radius: 10px;
            font-size: 12px;
            color: #666;
            font-weight: 600;
          }
        </style>
      </head>
      <body>
        <header>
          <div style="max-width: 1200px; margin: 0 auto;">
            <xsl:if test="sitemap:sitemapindex">
              <h1>Sitemap Index <span class="count-tag"><xsl:value-of select="count(sitemap:sitemapindex/sitemap:sitemap)"/> Sitemaps</span></h1>
            </xsl:if>
            <xsl:if test="sitemap:urlset">
              <h1>Sitemap <span class="count-tag"><xsl:value-of select="count(sitemap:urlset/sitemap:url)"/> URLs</span></h1>
            </xsl:if>
            <p class="desc">
              Generated by Active Away. This is an XML Sitemap, meant to be consumed by search engines like Google or Bing.<br/>
              You can find more information about XML Sitemaps at <a href="http://sitemaps.org" style="color:white; text-decoration: underline;">sitemaps.org</a>.
            </p>
          </div>
        </header>
        <div id="content">
          <xsl:if test="sitemap:sitemapindex">
            <table cellpadding="0" cellspacing="0">
              <thead>
                <tr>
                  <th width="60%">Sitemap URL</th>
                  <th width="15%">Count</th>
                  <th width="25%">Last Updated</th>
                </tr>
              </thead>
              <tbody>
                <xsl:for-each select="sitemap:sitemapindex/sitemap:sitemap">
                  <tr>
                    <td>
                      <xsl:variable name="itemURL">
                        <xsl:value-of select="sitemap:loc"/>
                      </xsl:variable>
                      <a href="{$itemURL}">
                        <xsl:value-of select="sitemap:loc"/>
                      </a>
                    </td>
                    <td>
                      <xsl:if test="@aa:count">
                        <span class="url-count"><xsl:value-of select="@aa:count"/></span>
                      </xsl:if>
                    </td>
                    <td>
                      <xsl:value-of select="substring(sitemap:lastmod,0,11)"/>
                    </td>
                  </tr>
                </xsl:for-each>
              </tbody>
            </table>
          </xsl:if>
          
          <xsl:if test="sitemap:urlset">
            <table cellpadding="0" cellspacing="0">
              <thead>
                <tr>
                  <th width="55%">URL</th>
                  <th width="15%">Priority</th>
                  <th width="15%">Change Freq</th>
                  <th width="15%">Last Updated</th>
                </tr>
              </thead>
              <tbody>
                <xsl:for-each select="sitemap:urlset/sitemap:url">
                  <tr>
                    <td>
                      <xsl:variable name="itemURL">
                        <xsl:value-of select="sitemap:loc"/>
                      </xsl:variable>
                      <a href="{$itemURL}" target="_blank">
                        <xsl:value-of select="sitemap:loc"/>
                      </a>
                    </td>
                    <td>
                      <xsl:value-of select="sitemap:priority"/>
                    </td>
                    <td>
                      <xsl:value-of select="sitemap:changefreq"/>
                    </td>
                    <td>
                      <xsl:value-of select="substring(sitemap:lastmod,0,11)"/>
                    </td>
                  </tr>
                </xsl:for-each>
              </tbody>
            </table>
          </xsl:if>
        </div>
        <div style="text-align: center; padding-bottom: 40px; color: #999; font-size: 12px;">
          © 2025 Active Away
        </div>
      </body>
    </html>
  </xsl:template>
</xsl:stylesheet>